### PR TITLE
add git repo finding to workspace root + temporary fix for issue #3

### PR DESCRIPTION
**Pull request by cyuria**
add some code to search for a git repo as well as a temporary fix for issue #3 on windows.

### CODE REVIEW

**Comment by cyuria** [comment]
This should also maybe help with issue #2

**Comment by ObserverOfTime** [comment]
I'll merge the fix for #3.

Git workspace detection should be implemented with `vim.fs.find` and also return the URL.

**Comment by ObserverOfTime** [comment]
Also note that the fix will most likely result in a false positive when the plugin starts before Discord.

**Comment by cyuria** [comment]
> Git workspace detection should be implemented with `vim.fs.find` and also return the URL.

so something like this, but also with a `git remote show origin` or similar to get the url?

```lua
---@param path string?
---@return string?
local function find_git_repo_dir(path)
    -- use current working directory if no path specified
    path = path or vim.loop.cwd()

    local repos = vim.fs.find('.git', {
        upward = true,
        stop = vim.loop.os_homedir(),
        path = path
    })

    return repos[1]
end
```

**Pull request closed without merging**
